// <auto-generated />
using System;
using CareerQuest.Modules.Players.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerQuest.Modules.Players.Infrastructure.Database.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    partial class PlayersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("players")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "players");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "players");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "players");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "players");
                });

            modelBuilder.Entity("CareerQuest.Modules.Players.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CareerStage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("career_stage");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Headline")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("headline");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<DateTime>("LastActiveAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_active_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("CareerStage")
                        .HasDatabaseName("ix_players_career_stage");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_players_display_name");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_players_email");

                    b.ToTable("players", "players");
                });

            modelBuilder.Entity("CareerQuest.Modules.Players.Domain.Players.PlayerProgression", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("CurrentLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_level");

                    b.Property<int>("CurrentXp")
                        .HasColumnType("integer")
                        .HasColumnName("current_xp");

                    b.Property<int>("SkillPoints")
                        .HasColumnType("integer")
                        .HasColumnName("skill_points");

                    b.Property<int>("TotalXp")
                        .HasColumnType("integer")
                        .HasColumnName("total_xp");

                    b.Property<int>("XpToNextLevel")
                        .HasColumnType("integer")
                        .HasColumnName("xp_to_next_level");

                    b.HasKey("PlayerId")
                        .HasName("pk_player_progressions");

                    b.HasIndex("CurrentLevel")
                        .HasDatabaseName("ix_player_progressions_current_level");

                    b.HasIndex("TotalXp")
                        .HasDatabaseName("ix_player_progressions_total_xp");

                    b.ToTable("player_progressions", "players");
                });

            modelBuilder.Entity("CareerQuest.Modules.Players.Domain.Players.Player", b =>
                {
                    b.OwnsMany("CareerQuest.Modules.Players.Domain.Players.PlayerClass", "Classes", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("player_id");

                            b1.Property<int>("ClassType")
                                .HasColumnType("integer")
                                .HasColumnName("class_type");

                            b1.HasKey("PlayerId", "ClassType")
                                .HasName("pk_player_classes");

                            b1.HasIndex("ClassType")
                                .HasDatabaseName("ix_player_classes_class_type");

                            b1.ToTable("player_classes", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_classes_players_player_id");
                        });

                    b.OwnsMany("CareerQuest.Modules.Players.Domain.Players.PlayerSpecialization", "Specializations", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("player_id");

                            b1.Property<int>("SpecializationType")
                                .HasColumnType("integer")
                                .HasColumnName("specialization_type");

                            b1.HasKey("PlayerId", "SpecializationType")
                                .HasName("pk_player_specializations");

                            b1.HasIndex("SpecializationType")
                                .HasDatabaseName("ix_player_specializations_specialization_type");

                            b1.ToTable("player_specializations", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_specializations_players_player_id");
                        });

                    b.OwnsOne("CareerQuest.Modules.Players.Domain.Players.PlayerStatistics", "Statistics", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("TotalAchievementsUnlocked")
                                .HasColumnType("integer")
                                .HasColumnName("total_achievements_unlocked");

                            b1.Property<int>("TotalApplications")
                                .HasColumnType("integer")
                                .HasColumnName("total_applications");

                            b1.Property<int>("TotalCommits")
                                .HasColumnType("integer")
                                .HasColumnName("total_commits");

                            b1.Property<int>("TotalNetworkingInteractions")
                                .HasColumnType("integer")
                                .HasColumnName("total_networking_interactions");

                            b1.Property<int>("TotalPostsPublished")
                                .HasColumnType("integer")
                                .HasColumnName("total_posts_published");

                            b1.Property<int>("TotalQuestsCompleted")
                                .HasColumnType("integer")
                                .HasColumnName("total_quests_completed");

                            b1.HasKey("PlayerId")
                                .HasName("pk_player_statistics");

                            b1.ToTable("player_statistics", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_statistics_players_id");
                        });

                    b.OwnsOne("CareerQuest.Modules.Players.Domain.Players.PlayerStreak", "Streak", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<int>("CurrentDays")
                                .HasColumnType("integer")
                                .HasColumnName("current_days");

                            b1.Property<decimal>("CurrentMultiplier")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("current_multiplier");

                            b1.Property<DateTime>("LastActivityDateUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_activity_date_utc");

                            b1.Property<int>("LongestDays")
                                .HasColumnType("integer")
                                .HasColumnName("longest_days");

                            b1.HasKey("PlayerId")
                                .HasName("pk_player_streaks");

                            b1.ToTable("player_streaks", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_streaks_players_id");
                        });

                    b.OwnsMany("CareerQuest.Modules.Players.Domain.Players.PlayerTitle", "Titles", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("player_id");

                            b1.Property<int>("TitleType")
                                .HasColumnType("integer")
                                .HasColumnName("title_type");

                            b1.Property<bool>("IsCurrent")
                                .HasColumnType("boolean")
                                .HasColumnName("is_current");

                            b1.Property<DateTime>("UnlockedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("unlocked_at_utc");

                            b1.HasKey("PlayerId", "TitleType")
                                .HasName("pk_player_titles");

                            b1.HasIndex("IsCurrent")
                                .HasDatabaseName("ix_player_titles_is_current");

                            b1.HasIndex("TitleType")
                                .HasDatabaseName("ix_player_titles_title_type");

                            b1.ToTable("player_titles", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_titles_players_player_id");
                        });

                    b.Navigation("Classes");

                    b.Navigation("Specializations");

                    b.Navigation("Statistics");

                    b.Navigation("Streak");

                    b.Navigation("Titles");
                });

            modelBuilder.Entity("CareerQuest.Modules.Players.Domain.Players.PlayerProgression", b =>
                {
                    b.HasOne("CareerQuest.Modules.Players.Domain.Players.Player", null)
                        .WithOne("Progression")
                        .HasForeignKey("CareerQuest.Modules.Players.Domain.Players.PlayerProgression", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_progressions_players_player_id");

                    b.OwnsMany("CareerQuest.Modules.Players.Domain.Players.XpTransaction", "Transactions", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid")
                                .HasColumnName("player_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("action");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasColumnName("amount");

                            b1.Property<DateTime>("EarnedAtUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("earned_at_utc");

                            b1.Property<float>("Multiplier")
                                .HasColumnType("real")
                                .HasColumnName("multiplier");

                            b1.Property<string>("Notes")
                                .HasColumnType("text")
                                .HasColumnName("notes");

                            b1.HasKey("PlayerId", "Id")
                                .HasName("pk_player_xp_transactions");

                            b1.ToTable("player_xp_transactions", "players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId")
                                .HasConstraintName("fk_player_xp_transactions_player_progressions_player_id");
                        });

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CareerQuest.Modules.Players.Domain.Players.Player", b =>
                {
                    b.Navigation("Progression");
                });
#pragma warning restore 612, 618
        }
    }
}
