// <auto-generated />
using System;
using CareerQuest.Modules.Users.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareerQuest.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260509164423_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("CareerQuest.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("CareerQuest.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:search"
                        },
                        new
                        {
                            Code = "users:create"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "users:delete"
                        },
                        new
                        {
                            Code = "user-profiles:read"
                        },
                        new
                        {
                            Code = "user-profiles:update"
                        },
                        new
                        {
                            Code = "user-classes:read"
                        },
                        new
                        {
                            Code = "user-classes:add"
                        },
                        new
                        {
                            Code = "user-classes:remove"
                        },
                        new
                        {
                            Code = "user-specializations:read"
                        },
                        new
                        {
                            Code = "user-specializations:add"
                        },
                        new
                        {
                            Code = "user-specializations:remove"
                        },
                        new
                        {
                            Code = "career-stages:read"
                        },
                        new
                        {
                            Code = "career-stages:update"
                        },
                        new
                        {
                            Code = "progression:read"
                        },
                        new
                        {
                            Code = "progression:earn-xp"
                        },
                        new
                        {
                            Code = "progression:update"
                        },
                        new
                        {
                            Code = "progression:spend-skill-points"
                        },
                        new
                        {
                            Code = "quests:read"
                        },
                        new
                        {
                            Code = "quests:complete"
                        },
                        new
                        {
                            Code = "quests:create"
                        },
                        new
                        {
                            Code = "quests:update"
                        },
                        new
                        {
                            Code = "boss-battles:read"
                        },
                        new
                        {
                            Code = "boss-battles:complete"
                        },
                        new
                        {
                            Code = "achievements:read"
                        },
                        new
                        {
                            Code = "achievements:unlock"
                        },
                        new
                        {
                            Code = "skill-trees:read"
                        },
                        new
                        {
                            Code = "skill-trees:unlock"
                        },
                        new
                        {
                            Code = "skill-trees:reset"
                        },
                        new
                        {
                            Code = "activities:read"
                        },
                        new
                        {
                            Code = "activities:create"
                        },
                        new
                        {
                            Code = "activities:update"
                        },
                        new
                        {
                            Code = "networking:read"
                        },
                        new
                        {
                            Code = "networking:create"
                        },
                        new
                        {
                            Code = "content:read"
                        },
                        new
                        {
                            Code = "content:publish"
                        },
                        new
                        {
                            Code = "content:update"
                        },
                        new
                        {
                            Code = "opportunities:read"
                        },
                        new
                        {
                            Code = "opportunities:create"
                        },
                        new
                        {
                            Code = "opportunities:update"
                        },
                        new
                        {
                            Code = "opportunities:delete"
                        },
                        new
                        {
                            Code = "clients:read"
                        },
                        new
                        {
                            Code = "clients:create"
                        },
                        new
                        {
                            Code = "clients:update"
                        },
                        new
                        {
                            Code = "weekly-reviews:read"
                        },
                        new
                        {
                            Code = "weekly-reviews:create"
                        },
                        new
                        {
                            Code = "dashboard:read"
                        },
                        new
                        {
                            Code = "analytics:read"
                        },
                        new
                        {
                            Code = "roles:manage"
                        },
                        new
                        {
                            Code = "permissions:manage"
                        });
                });

            modelBuilder.Entity("CareerQuest.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Member"
                        },
                        new
                        {
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("CareerQuest.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-profiles:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-profiles:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-classes:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-classes:add",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-specializations:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "user-specializations:add",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "career-stages:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "career-stages:update",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "progression:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "quests:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "quests:complete",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "boss-battles:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "boss-battles:complete",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "achievements:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "skill-trees:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "skill-trees:unlock",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "activities:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "activities:create",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "networking:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "networking:create",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "content:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "content:publish",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "opportunities:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "opportunities:create",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "weekly-reviews:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "weekly-reviews:create",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "dashboard:read",
                            RoleName = "Member"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:search",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-profiles:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-profiles:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-classes:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-classes:add",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-classes:remove",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-specializations:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-specializations:add",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "user-specializations:remove",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "career-stages:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "career-stages:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "progression:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "progression:earn-xp",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "progression:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "progression:spend-skill-points",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "quests:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "quests:complete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "quests:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "quests:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "boss-battles:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "boss-battles:complete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "achievements:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "achievements:unlock",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "skill-trees:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "skill-trees:unlock",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "skill-trees:reset",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "activities:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "activities:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "activities:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "networking:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "networking:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "content:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "content:publish",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "content:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "opportunities:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "opportunities:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "opportunities:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "opportunities:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "clients:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "clients:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "clients:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "weekly-reviews:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "weekly-reviews:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "dashboard:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "analytics:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "roles:manage",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "permissions:manage",
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("roles_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("CareerQuest.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("CareerQuest.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("CareerQuest.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("CareerQuest.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
